# merging.ipynb

Merging the datasets from youtube and tiktok

In [2]:
import pandas as pd

In [3]:
df_tiktok = pd.read_csv("data/tiktok_clean_data.csv")
df_tiktok.head(2)

,Unnamed: 0,source,tag,video_id,post_date_utc,description,text_language,category_type,is_aigc,aigc_description,...,is_reviewing,likes,comments,shares,views,author_follower_count,author_following_count,author_total_likes,author_video_count,datetime
0,0,TikTok,OliviaHenderson,7573038672262466830,2027-03-20 14:31:59.722000+00:00,When running to social media goes wrong. DoorD...,en,114,False,NaN,...,False,2019,306,27,49300,62600,765,1000000,687,2025-11-15 13:37:48
1,1,TikTok,OliviaHenderson,7591774242346257677,2027-05-11 07:20:27.720000+00:00,Police have now confirmed new details in the O...,en,114,False,NaN,...,False,52,3,0,4133,10400,0,9322,182,2026-01-05 01:21:23

In [4]:
df_tiktok.columns

Index(['Unnamed: 0', 'source', 'tag', 'video_id', 'post_date_utc',
       'description', 'text_language', 'category_type', 'is_aigc',
       'aigc_description', 'collected', 'is_reviewing', 'likes', 'comments',
       'shares', 'views', 'author_follower_count', 'author_following_count',
       'author_total_likes', 'author_video_count', 'datetime'],
      dtype='object')

In [5]:
# keeping only the relevant columns for the tiktok data
df_tiktok = df_tiktok[["source",
                       "tag",
                       "video_id",
                       "description",
                       "likes",
                       "comments",
                       "shares",
                       "views",
                       "author_follower_count",
                       "author_video_count",
                       "datetime"]]
df_tiktok.columns

Index(['source', 'tag', 'video_id', 'description', 'likes', 'comments',
       'shares', 'views', 'author_follower_count', 'author_video_count',
       'datetime'],
      dtype='object')

In [6]:
df_yt = pd.read_csv("data/other_sources/yt_dordash_girl_video_finalAGGR_clean.csv")
df_yt.head(2)

,video_id,url,video_title,channel_id,channel_title,publish_date,description,channel_following,duration,like_count,comment_count,view_count,accessed_at,transcript
0,IgQK3tz-fKM,https://www.youtube.com/watch?v=IgQK3tz-fKM,Инцидент с Пенсилом: Великая Ошибка DoorDash ✏️,UCDDZOBAdDlPbUA4z42r_wvw,i11ushenka,10-23-25,"Мне очень интересно, чем это закончится. У муж...",2330000,00:00:44,300455,6273,12525460,2026-02-05 15:44:03.401564,NaN
1,4pM7DLEL7xA,https://www.youtube.com/watch?v=4pM7DLEL7xA,The Doordash Girl Situation is INSANE😭 #roblox...,UCJhGkYMvUaWJ3mb1FhOMkTw,Sammy,10-19-25,NaN,56100,00:00:35,104516,1709,4152571,2026-02-05 15:44:03.401573,"Bro, the Door Dash girl situation is crazy. So..."

In [7]:
df_yt.columns

Index(['video_id', 'url', 'video_title', 'channel_id', 'channel_title',
       'publish_date', 'description', 'channel_following', 'duration',
       'like_count', 'comment_count', 'view_count', 'accessed_at',
       'transcript'],
      dtype='object')

In [8]:
# keeping only the relevant columns for the youtube data
df_yt["source"] = "Youtube"
df_yt = df_yt.drop(labels=["url", "accessed_at", "channel_id", "duration"], axis=1)
df_yt.columns

Index(['video_id', 'video_title', 'channel_title', 'publish_date',
       'description', 'channel_following', 'like_count', 'comment_count',
       'view_count', 'transcript', 'source'],
      dtype='object')

In [9]:
# renaming columns to align with tiktok
rename_dict = {
    'video_id': 'video_id',
    'publish_date': 'datetime',
    'description': 'description',
    'channel_following': 'author_follower_count',
    'like_count': 'likes',
    'comment_count': 'comments',
    'view_count': 'views',
}

df_yt_renamed = df_yt.rename(columns=rename_dict)

# fixing datetime
df_yt_renamed['datetime'] = pd.to_datetime(df_yt_renamed['datetime'], format='%m-%d-%y').dt.date
df_tiktok['datetime'] = pd.to_datetime(df_tiktok['datetime']).dt.date


# combining the data
df_combined = pd.concat([df_tiktok, df_yt_renamed], ignore_index=True)
df_combined

,source,tag,video_id,description,likes,comments,shares,views,author_follower_count,author_video_count,datetime,video_title,channel_title,transcript
0,TikTok,OliviaHenderson,7573038672262466830,When running to social media goes wrong. DoorD...,2019,306,27.0,49300,62600,687.0,2025-11-15,NaN,NaN,NaN
1,TikTok,OliviaHenderson,7591774242346257677,Police have now confirmed new details in the O...,52,3,0.0,4133,10400,182.0,2026-01-05,NaN,NaN,NaN
2,TikTok,OliviaHenderson,7573068947105320222,#doordash #oliviahenderson #arrested,195,20,12.0,3048,60400,914.0,2025-11-15,NaN,NaN,NaN
3,TikTok,OliviaHenderson,7573593663788436749,DoorDash girl ARRESTED for TWO felonies!! #doo...,156,14,9.0,20300,10300,83.0,2025-11-17,NaN,NaN,NaN
4,TikTok,OliviaHenderson,7581702595585068319,DoorDash girl Olivia Henderson was seen in cou...,25,6,1.0,13400,2,9.0,2025-12-08,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
424,Youtube,NaN,2ytZhL25V4w,"The Viral DoorDash girl, Olivia Rose Henderson...",1715,892,NaN,35947,29500,NaN,2025-12-11,The DoorDash Girl LOSES IT in COURT,CamNuggets,NaN
425,Youtube,NaN,wHOGG1-RN5U,Olivia Henderson has her day in court and tik ...,63,25,NaN,2647,119,NaN,2025-12-15,Doordash girl has her day in court,Kage Lucas.commentary,last time on Tik Tok >> of essay by a Door Das...
426,Youtube,NaN,7N4tatSKaRI,Silent in Court DoorDash Driver's TikTok Claim...,49,12,NaN,3508,3010,NaN,2025-12-16,Silent in Court DoorDash Driver&#39;s TikTok C...,Lisa Harvey,The first look at 23-year-old Olivia Henderson...
427,Youtube,NaN,wXyMT1ghH-E,"The viral saga of Olivia Henderson, the DoorDa...",14,7,NaN,553,126,NaN,2025-12-29,Olivia Henderson RETURNS To Court After Viral ...,FameQuake,Best comment gets pinned. Good luck. The drama...
428,Youtube,NaN,6hceg0riX-Y,This video outlines some of the events of Oliv...,1,0,NaN,17,23,NaN,2025-12-15,Judge Is Not Playing Around With The Door Dash...,Rant Of The Day,The Asiggo City judge allowing News Channel 9 ...

In [10]:
# exporting

df_combined.to_csv("data/combined_data.csv")